language: java

jdk:
- oraclejdk8

branches:
  only:
  - master

install:
- mvn clean
- mvn package

deploy:
- provider: script
  skip_cleanup: true
  github_token: $GH_TOKEN
  script: "[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./travis-deploy.sh"
  on:
    branch: master
