language: java

jdk:
- oraclejdk8

branches:
  only:
  - master
  
env: 
  global: 
    - GIT_TAG= 'Jupiter(nukkit)-1.0-$TRAVIS_BUILD_NUMBER'
    - secure: $GH_TOKEN

install:
- mvn clean
- mvn package

before_deploy: 
  - mkdir packages
  - export JAR_FILE=$(ls target/nukkit-1.0-SNAPSHOT.jar)
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci-org"
  - git tag -a -m "Commit from Travis CI build $TRAVIS_BUILD_NUMBER" ${GIT_TAG}
  - git push --quiet https://$GH_TOKEN@github.com/JupiterDevelopmentTeam/Jupiter.git --tags 2> /dev/null
deploy: 
  provider: releases
  skip_cleanup: true
  api_key: 
    secure: $GH_RELEASE_TOKEN
  file:
    - ${JAR_FILE}
  on: 
    branch: master