language: java

jdk:
- oraclejdk8

branches:
  only:
  - master

install:
- mvn clean
- mvn package

deploy:
- provider: script
  skip_cleanup: true
  github_token: $GH_TOKEN
  script: 'bash ./travis-deploy.sh'
  on:
    branch: master
